---
- name: Provision Cassandra cluster security group
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create security group roles
      local_action:
        module: ec2_group
        name: "{{security_group}}"
        region: "{{region}}"
        vpc_id: "{{vpc_id}}"
        description: "Cassandra Cluster Security Group"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8888
            to_port: 8888
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8081
            to_port: 8081
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 7000
            to_port: 7000
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 7001
            to_port: 7001
            group_name: "{{security_group}}"
          - proto: tcp
            from_port: 7199
            to_port: 7199
            group_name: "{{security_group}}"
          - proto: tcp
            from_port: 9042
            to_port: 9042
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 9160
            to_port: 9160
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 61620
            to_port: 61620
            group_name: "{{security_group}}"
          - proto: tcp
            from_port: 61621
            to_port: 61621
            group_name: "{{security_group}}"
          - proto: udp
            from_port: 25826
            to_port: 25826
            cidr_ip: 0.0.0.0/0
          - proto: udp
            from_port: 5555
            to_port: 5555
            group_name: "{{security_group}}"
          - proto: tcp
            from_port: 5555
            to_port: 5555
            group_name: "{{security_group}}"
          - proto: udp
            from_port: 5556
            to_port: 5556
            group_name: "{{security_group}}"
          - proto: tcp
            from_port: 4567
            to_port: 4567
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 2003
            to_port: 2003
            group_name: "{{security_group}}"
          - proto: tcp
            from_port: 5000
            to_port: 5000
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 10000
            to_port: 10000
            cidr_ip: 0.0.0.0/0
          - proto: icmp
            from_port: -1
            to_port: -1
            cidr_ip: 0.0.0.0/0

        rules_egress:
          - proto: all
            type: all
            cidr_ip: 0.0.0.0/0
